openapi: "3.0.0"
servers:
  - url: http://localhost:8080
info:
  version: 0.0.1
  title: Nobis API
tags:
  - name: Tags controller

paths:
  /api/tags/add/{userId}:
      put:
        summary: Add tags by userId
        operationId: addTags
        parameters:
          - in: path
            name: userId
            schema:
              type: string
            required: true
            description: Id of the user to add tags
        requestBody:
          description: An array of tags to add
          required: true
          content:
            application/json:
              schema:
                  type: array
                  items:
                    type: string
        responses:
          '200':
            description: OK
          '400':
            description: Bad request. Invalid userId.
          '404':
            description: A user with the specified ID was not found.
          '500':
            description: Unexpected error.

  /api/tags/get/{userId}:
      get:
        summary: Get vector for current tags by userId
        parameters:
          - in: path
            name: userId
            schema:
              type: string
            required: true
            description: Id of the user to get current vector
        operationId: getVector
        responses:
          '200':
            description: Expected response to a valid request
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: number
                    format: double
          '400':
            description: Bad request. Invalid userId.
          '404':
            description: A user with the specified ID was not found.
          '500':
            description: Unexpected error.
                  
  /api/tags/remove/{userId}:
      post:
        summary: Remove tags by userId
        parameters:
          - in: path
            name: userId
            schema:
              type: string
            required: true
            description: Id of the user to remove tags
        requestBody:
          description: An array of tags to remove
          required: true
          content:
            application/json:
              schema:
                  type: array
                  items:
                    type: string
        operationId: removeTags
        responses:
          '200':
            description: OK
          '400':
            description: Bad request. Invalid userId.
          '404':
            description: A user with the specified ID was not found.
          '500':
            description: Unexpected error.